module.exports = {
    CONTACT_NUMBER : 0000000000,
    EMPTY_STRING : '',
    ADMIN_ROLE : 'ADMIN',
    USER_ROLE : 'USER',
    LANDMARK : '',
    PRODUCT_NAME : '',
    PRODCUT_PRICE : 10.0,
    PRODUCT_CATEGORY : 'MISCELLANEOUS',
    PRODUCT_DESCRIPTION : '',
    PRODUCT_IMAGE_URL : 'IMAGE URL'
}